sudo: false
language: node_js
addons:
  sauce_connect: true
matrix:
  include:
  - node_js: node
    addons:
      sauce_connect: true
    before_script:
    - npm run http-server &
    - sleep 2
    script: npm run ui
env:
  global:
  - secure: nvw2GlMI0kyZ519cC8d2ktOQM8T4jb9P1ePKhl6qfQJdP0Kns+3qrDj7BLa0lE50WaVtC4JMrtqh2QUhu/PLkvWzMhfngtbrW/v2jOwTb2EQa50FHKHXvtMeAG/ZFN69NHCMnll9TGxD4ZGy6YXDr8FWL7t88gTP18ZNVErVLYtDZfWvlADqC3XLmQTL5QkOTyOx0QVnwclh18q5sykH2f4KEnXfir8BM9ozMFs9qAMWaqB50NCOu8wWwk8CVDdYJ0gSvxIEqE22YXEqPWvWAiQ2oY43Ifwo4PWDoPzeVUXiYuXvxu1Ss3wNy5vasyFGcX5No0Nh6/VjUenTMnGKaA6IU3uoSNyOwplCGh4XCK+w23aUxlSR+IV4lWLZPv+BRKOUe7UDyChuZIOvtgaDlr6Y6Ro9K9i/3NEhPmB9HKSB1cWptQdljBxwvupF+t0neu072okjVYU1gWhcWOUzukcLJoMGumJrFO+UMKjVb0brFYNwaU85g3GO8YBvQDv8nBMAPHmpiPR2/Gj+kRV/FR9ngF9HJ6njhG2ySLuHla2bjwtfyxPAqueE5OF8MhLZwrBST/+Zzih1crw5M97PuPB9tuY3pYxMoifyK0NiI7uk9/mWULzgRos0yOko5CV4ofu97Wcflk3T/QJgn5jiMhX5iKYkURKKCmew9q74NV0=
  - secure: JytvOuL6xKqGcLlrnOjDt3IhwkT5eZ948ZE8ubcw4oOoTUsqe0QMrtaifv5MmIHHWTf3Lg0dzsN85sYvBJWpo0RO/3q+xLuimEOCdxRASEyynXm0P0gHjAu/h2VPI65uu4vlt+yzO7tQ8HIXWDOQ0Mbac3bhZJ1wXaKYKoVdjGKfDw5rN6/f2Qak6C5hx+vUmDblO6D5qLDCuGLvqOhRY3pt1GQDgArQACKKLa/TEhGjxRWtmoE6Y5gyoTJljq3RLY23o1T8Gy9jEvXdnmN2FpYkFQDDGyDosP4FaUcx4RNel9Rx4WanYEJMNXb6ot1rUD1kBCFKNTfIA5SkBXF5Ye3nyjSomUptgQDMvb1U9OE34kvLiKo2bUk32+0pygqQdrTT+DEYHlY/JRZo++e1uIyJtkeVDbg1gqAgnrJ1eUvM3YwUwTLjotsRqNvd5IDMJwuQZDLEpG0/2nLv1PshkG0yZQN7+iiaBR3EWwnjTQJpS2wCTZ/s0CObF5F1o5aLsNIUaR+JW4kgbA03Ak+xcwXbuudJBucQ0iIkVOWBA6U/X1lS6pZcTNTgSPwubLiutnuIDqO2aL3Ze0lwr2QSMRhQEXcH609o61wN3wN46PIzNEbNxu0izmLMdgzEFtjxhnsxgyUADjO6Gi/iCJArXUbFDmN4anqPnLl769Ardlw=
